apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cost-optimized-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloud-cost-app
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.monitoring.svc:9090
      query: sum(rate(container_cpu_usage_seconds_total[1m])) by (pod)
      threshold: "0.7"
